-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE // 소수 둘째짜리에서 반올림 하는 방법
    FROM REST_INFO I
        INNER JOIN REST_REVIEW V ON I.REST_ID = V.REST_ID // 내부조인할때 ON으로 해주어야함
    WHERE  I.ADDRESS LIKE '서울%' // 서울로 끝나는 주소 
    GROUP BY
    I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS
    ORDER BY SCORE DESC,I.FAVORITES DESC 
    
